### ISSUE TITLE
ListView Command Set extension not loading on a specific list

### ISSUE THREAD

**Issue by vladigubler** [SharePoint/sp-dev-docs#10074]
### Target SharePoint environment

SharePoint Online

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [X] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [ ] mobile (iOS/iPadOS)
- [ ] mobile (Android)
- [ ] not applicable
- [ ] other (enter in the "Additional environment details" area below)

### Additional environment details

- browser version : latest Edge and Chrome (but not Firefox)
- SPFx version: 1.15
- Node.js version: 14.21.3
- New Lists interface

### Describe the bug / error

On one specific Custom list only the SPFx extensions do not load. Works well on other lists and, strangely, works in Firefox.
When it doesn't work, the following lines are found in Console for each one of the extensions:

"A preload for 'https://storage.infowisesolutions.com/ufspfx/v1400/infowise-design.js' is found, but is not used due to an unknown reason."

### Steps to reproduce

Not sure how to reproduce, but it consistently doesn't load on a particular list, but works on all the other lists within the same site, with or without the new Lists interface. This is a simple SPFx list extensions that adds some buttons to the toolbar.

This is the error:
![errspfx](https://github.com/user-attachments/assets/b6385859-0cdf-406e-be78-332a07454942)

### Expected behavior

Loads on all lists in the site.

**Comment by Kolyangus** [comment]
I would just add that we have also been experiencing similar issues with this meaning that customers are unable to perform functionality.

I did see a closed issue with relation to embedded pages for Command Set #10057 as this is a fairly new issue that has been closed and whether this had an impact causing the above?

**Comment by vladigubler** [comment]
As far as I can see, it affects certain lists, but not others. I can't see any difference between the lists, same template, same everything. It is persistent though. The affected lists stay affected, no matter what I do. 
The only (imperfect) workaround is to add a custom column to the view, which forces the regular, not MS Lists, interface.

**Comment by reedpamsft** [comment]
Thanks folks!  We have a fix for the issue, and just need to evaluate our options for rolling it out.  Workaround would be to visit the list/library in "full" mode (ie: not in a web part).

**Comment by vladigubler** [comment]
We are visiting it in full mode, we don't use web parts for this. It is an extremely wide-spread issue and I feel it's growing every day, probably as more tenants get the newest UI.

**Comment by vladigubler** [comment]
Note, I also get this sometimes: A preload for 'https://storage.infowisesolutions.com/ufspfx/v1400/infowise-slp.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute. I have no idea where it's coming from and why it would suddenly ask for this attribute. It's something on your side.

**Comment by vladigubler** [comment]
And there is also this now: The resource at “https://storage.infowisesolutions.com/ufspfx/v1400/infowise-design.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.
This happens in Firefox.

**Comment by vladigubler** [comment]
Also, today the issue spread to all lists using the MS Lists interface, please help!

**Comment by reedpamsft** [comment]
> And there is also this now: The resource at “[https://storage.infowisesolutions.com/ufspfx/v1400/infowise-design.js”](https://storage.infowisesolutions.com/ufspfx/v1400/infowise-design.js%E2%80%9D) preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. This happens in Firefox.

@vladigubler that seems unrelated; please feel free to open a new thread about those.

**Comment by reedpamsft** [comment]
@vladigubler okay, I'm really sorry, I'm getting this mixed up with another issue that came across my inbox... I'll send this to the appropriate folks.

**Comment by vladigubler** [comment]
@reedpamsft Is there any ETA when it's going to be fixed. According to our customers it stopped working within the last 24 hours on all the lists it previously worked on. I'm guessing an update was recently pushed out?

**Comment by natalieethell** [comment]
@vladigubler as discussed over mail, I believe this issue should be fixed now. We rolled back a change that caused a regression for this experience.

**Comment by Kolyangus** [comment]
I wasn't added to the mail correspondence but confirm from my side the issue appears to be resolved based on the roll back. Hopefully it's also solved for @vladigubler

**Comment by vladigubler** [comment]
Looking good! Was very impressed by the turnaround! I will have more people confirm it tomorrow.

Regards,

Vladimir Gubler

[signatureImage]
________________________________

**Comment by vladigubler** [comment]
Start about 2 days ago the issue is back, I'm guessing another faulty update?

**Comment by Olena-UMPQ** [comment]
I agree with @vladigubler. I'm struggling with this issue as well. 
Any ETA on the resolution?

**Comment by natalieethell** [comment]
Sorry for the disruption here! We are working to debug the issue and will post an update here.

**Comment by natalieethell** [comment]
@vladigubler @Olena-UMPQ We rolled back a change that seems to be causing this issue. Let me know if you are still seeing problems!

**Comment by vladigubler** [comment]
It seems to be ok, thanks

**Comment by Olena-UMPQ** [comment]
Works for me too! Thank you for the update. I've communicated this find to users and waiting for the feedback.

**Comment by Ashlesha-MSFT** [comment]
Hello @vladigubler,
Thank you for bringing this issue to our attention. We will look into it and get back to you shortly.

**Comment by Ashlesha-MSFT** [comment]
@vladigubler,
It appears that the issue has already been resolved. Could you please close the issue?

Thank you!
