### ISSUE TITLE
SPFx package : Upload to app catalog fails

### ISSUE THREAD

**Issue by vipulkelkar** [SharePoint/sp-dev-docs#1318]
#### Category
- [ ] Question
- [ ] Typo
- [X ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

The SPPKG file should get uploaded to the App catalog without any issues

#### Observed Behavior

Error in uploading the file

![image](https://user-images.githubusercontent.com/13727430/35848624-ca6f6e32-0b44-11e8-96e7-7ff644602430.png)

#### Steps to Reproduce

Did some code changes to an existing SPFx webpart. The code builds, bundles and packages without any errors (except for a few warning of TSlint - semi colon missing). Tried to replace the existing SPPKG file of the webpart in the app catalog. Got the above error. Deleted the existing package file from the app catalog and also from the Recycle bin and tried again. still the same !

**Comment by BigEaseGueldi** [comment]
Same for me (probably everyone else). Of course this problem occurs when you are in the roll out phase of an important project. :-)

-> "we expect this process to take a few days" was not what I was hoping for ;-)

![sp128660](https://user-images.githubusercontent.com/17311219/35849657-a5f6705e-0b22-11e8-9316-5a28d53c4391.jpg)

Any more specific information regarding this? @VesaJuvonen ?

**Comment by db3005** [comment]
We got the exact same issue today, also changed some code in a spfx webpart, rebuild the solution and got this error after uploading the file:

Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"Unknown Status Module: 33 Message: 134"}}}

We tried to publish the package via powershell and directly in the app catalog resulting in the same error

**Comment by vipulkelkar** [comment]
Ah Yes, so i missed that advisory !

**Comment by marloesdekrom** [comment]
I've got the exact same issue. Hopefully it is fixed soon.

**Comment by dlwDenysma** [comment]
Same here :( Extremely inconvenient when fixing last issues before go/no-go live...

**Comment by wictorwilen** [comment]
Same here...can't deploy...missing deadline...

**Comment by pdemro** [comment]
Same issue since Monday for us

**Comment by VesaJuvonen** [comment]
This is, unfortunately, impacting both SharePoint add-ins and SharePoint Framework solutions, like communicated in the Tenant Admin message center with the SP128660 (screenshot above). We are working on getting this resolved asap, but do not currently have an ETA which can be shared here.

**Comment by trillian74** [comment]
Oh lord... major demo with Statoil tomorrow and we cannot get our massive effort out on the tenant...

**Comment by BigEaseGueldi** [comment]
Wondering whether switching the "componentType" in *.manifest.json to "Library" and then load the stuff manually on a classic page would be a workaround.

**Comment by trillian74** [comment]
Any news?

**Comment by VesaJuvonen** [comment]
@trillian74 there is internal progress on getting this resolved, but we can't give yet provide exact ETA.

**Comment by dougraheem** [comment]
Same issue. I bang my head against the wall over and over . Then found out there is an advisory. Interestingly, my developer tenant does not have an SharePoint Online Advisory but production tenant does. I believe issue is happening across all tenants.

**Comment by Christian-Stahl** [comment]
Same here. Hope it will work soon, at least we got our workbench to play with in the meantime :)

**Comment by dougraheem** [comment]
Use hosted workbench to in case web part is list data driven :)

**Comment by tdwhite0** [comment]
Surprised this is not getting more attention, its a pretty big showstopper.

**Comment by jonathanhotono** [comment]
I got the same issue too.
![image](https://user-images.githubusercontent.com/6864547/35896363-e8f7243c-0c0f-11e8-81cc-206ab4a79c78.png)

**Comment by rgarita** [comment]
Just to add more pressure,, We are being also impacted by this issue. an ETA will be appreciated....

**Comment by michel-weber** [comment]
Same here: All our automated deployments fail on all tenants (3). 

We also tried to manually upload and it fails.
We are just lucky that we don't have any important rollouts just now.

I'm wondering why this is not covered by automated regression tests? As stated in the advisory, it is a coding error so this could have been prevented. 

I really hope that after this is resolved, steps are taken to prevent this to happen again.


Great work on all the features of the tenant and site collection app catalogs btw ... we use the ALM APIs to deploy (before I automated everything by using Selenium).

**Comment by VesaJuvonen** [comment]
Thanks everyone for your input on your observations. We are working hard to get this resolved worldwide asap. We will also make changes in our validation process for the future to minimize possibilities for similar issues. 

Thanks @michel-weber also on the feedback around the latest capabilities, always appreciated. We unfortunate cannot give exact ETA at this point.

**Comment by wictorwilen** [comment]
I can confirm that it is now working properly again on a few of my tenants

**Comment by michel-weber** [comment]
I can also confirm - it is working properly again on at least one of my tenants.

**Comment by BigEaseGueldi** [comment]
Jup, works again. European tenant.

**Comment by dlwDenysma** [comment]
Yes, working again! 👍

**Comment by VesaJuvonen** [comment]
Thanks for your status updates. The fix is being rolled out gradually cross tenants. We do not have an exact ETA for the fix being 100% available worldwide, but you will see tenants getting fixed gradually. Great that we are already seeing tenants getting back to normal business. We do apology inconvenience and are taking corrective actions for the future to avoid these kinds of issues.

**Comment by wictorwilen** [comment]
(see this as a positive thing - we're actually building SPFx stuff - for realz!)

**Comment by vipulkelkar** [comment]
Working in an Australian too..

**Comment by koskila** [comment]
Just got a confirmation our deployments (mainly European ones) are going through as well :)

**Comment by VesaJuvonen** [comment]
@wictorwilen - Trust me. We are aware how much SPFx is being used across the world (we track this closely with telemetry) and super happy with the massive growth and adoption curve. Obviously, these kind of issues does not help. Anything can always happen and the key is to learn from them to minimize future possibilities for same issues to occur again.

Appreciate the input from everyone.

**Comment by trillian74** [comment]
Thanks for getting IT up and running. Our demo is saved, bit a few new gray freight hairs gained

**Comment by jonathanhotono** [comment]
Still not working in my tenants (Australian servers).. I will try again tomorrow as probably this needs time to propagate.

**Comment by freedumz** [comment]
I don't know if it's link
I can install apps but when I try to run them (after their installations) on my PWA, I've a loading page and after that nothing
(I let it load during 5hours)

**Comment by Serhiy-Shekhovtsov** [comment]
We can't remove\upgrade any Add-in on SharePoint Online.

**Comment by Christian-Stahl** [comment]
Now working in an Europe as well, thanks for quick fixing this!.

**Comment by VesaJuvonen** [comment]
@freedumz and @Serhiy-Shekhovtsov - Would suggest to open up a new issue and provide sufficient amount of details around the issue. How things were installed, what they are and how you tried to use them. Since behavior is different than in this issue, it's better to open a new item, so that your tasks are not getting hidden/buried in comments. Thx.

**Comment by submarines-and** [comment]
All our apps are also stuck on "We're removing your app"; we started to remove them during the outage listed in this issue.

Is this a separate issue then, or will it be fixed by the same fix that is rolling out for this issue?

**Comment by VesaJuvonen** [comment]
@submarines-and - it would be helpful to report that as a separate issue, so that your findings are not getting hidden in this one.

Sure - this could be related on this particular issue, but - let’s track that as isolated item and rather reference this issue in details to provide the needed context and insights on what you are currently seeing. Thx.

**Comment by pdemro** [comment]
All of my tenants are still impacted by the issue.  Will continue to test as the day goes on.

**Comment by submarines-and** [comment]
This is now resolved for us, will also update [the other issue](https://github.com/SharePoint/sp-dev-docs/issues/1325)

**Comment by pdemro** [comment]
This looks stable for me today.  Thanks guys.

**Comment by bmanning31** [comment]
FYI, was working this morning.  now it's NOT working.  same errors as yesterday.

**Comment by phoegfeldt** [comment]
Europe: I have also had the issue all this week. I managed to get it to work one time yesterday and one time today. But all my other deployment fails. I just tried 30 minutes ago and it still fails.

**Comment by phoegfeldt** [comment]
I can't see this advisory in my Tenant Admin message center with the SP128660. I can only see MC... messages. If I look in my preferences everything is set to ON.

**Comment by phoegfeldt** [comment]
This morning it seems to be fine. So let us hope it stays like this.

**Comment by bmanning31** [comment]
Still not working today.  Only working for me 1 out every 10 tries.  Same exact error messages, same behaviour as last week.  Very frustrating...

**Comment by phoegfeldt** [comment]
Europe: I am also getting this error again just now. I can't deploy to my developer SharePoint server. I get same error again like last week: Error occurred in deployment step 'Install SharePoint Add-in': The remote server returned an error: (429).

**Comment by VesaJuvonen** [comment]
Closing this issue for now, since it was a wider issue on the server side, which has been fixed. @phoegfeldt - Can you submit a new issue with additional details. If you are getting 429 exceptions, that refers to throttling and it's a different scenario, That will help us to find the right people internally to track the issue. thx. 

Same for @bmanning31 - we would need more details on your exact issue, so would ask to open a new issue with additional details. Thx.
