### ISSUE TITLE
Latest version of SharePoint Framework components not provided on npmjs.com (1.4.0 => 1.5.0)

### ISSUE THREAD

**Issue by gszdev** [SharePoint/sp-dev-docs#1333]
#### Category
- [x] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior
Latest version of SharePoint Framework components on npmjs.com.
Please provide the same version of the SharePoint Framework components also on npmjs.com.

#### Observed Behavior
SharePoint online is using newer SharePoint Framework components.
Yeoman (latest version) is still using version 1.4.0 of @microsoft/sp-dialog, cause on npmjs.com version 1.4.0 is the latest one (see define("c0c518b8-701b-4f6f-956d-5782772bb731_**1.4.0**").
But SharePoint Online is using version 1.5.0 (see define("c0c518b8-701b-4f6f-956d-5782772bb731_**1.5.0**")

#### Steps to Reproduce
- create a new SPFx Package
- create a new Application Customizer Extension
- create a custom Dialog [Use custom dialog boxes with SharePoint Framework Extensions](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/using-custom-dialogs-with-spfx)
- create a button and Show the Dialog
- start debugging (using **gulp serve --config=<yourconfig>**)
- while debugging version 1.4.0 from the node_modules is used and your are getting not the same behavior as without debugging. You'll same strange erros showing dialogs. Dialogs are not showing, because react node is not available. ...

**Comment by mpasarin** [comment]
Thanks for your feedback.

The first issue, about the versioning, is by design. The bits that we release on the server are "future versions" compared to the npm packages. The server bits are always backwards compatible so anything you develop with the npm packages will work properly.

The second issue, regarding not being able to use dialogs when testing an SPFx extension is a real issue. It has been fixed and it will be rolling out to all tenants within 2 weeks.
I'll close this issue, but feel free to re-open if you can still reproduce it in 2 weeks.

**Comment by gszdev** [comment]
The issue still reproducable.
Dialogs not showing while debugging (using gulp serve --config=).
Version **1.4.1** (c0c518b8-701b-4f6f-956d-5782772bb731_**1.4.1**) is used.
