### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'consume' of undefined when trying to debug a web part using MSGraphClient in the hosted workbench

### ISSUE THREAD

**Issue by cythomli** [SharePoint/sp-dev-docs#2045]
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Be able to debug web part using MSGraphClient in the hosted workbench while serving from the local web server.

#### Observed Behavior

After adding the web part to the page, you get the following error in the console:
![image](https://user-images.githubusercontent.com/6519992/41439079-4331e766-6fde-11e8-845d-08da05bcd86d.png)

#### Steps to Reproduce

scaffold new project using generator v1.5.0 with a React web part
to the render method add:

const client: MSGraphClient = this.context.serviceScope.consume(MSGraphClient.serviceKey);
      client
     .api('/groups')
     .get((error, response: any, rawResponse?: any) => {
       alert(response);
      });

run gulp serve --nobrowser
in the hosted workbench, add the web part to the canvas
in the console you get the aforementioned error

**Comment by licythom** [comment]
Also, I tried the code in the link: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-msgraph

And it gave an error:

![image](https://user-images.githubusercontent.com/6519992/41491253-dc8ad016-70ac-11e8-9939-54af4d41de57.png)

**Comment by VesaJuvonen** [comment]
A fix is being made and is getting rolled out within next few days. Please do confirm is the issue is resolved or not within next 7 days. Thx.

**Comment by licythom** [comment]
Issue still exists. Thanks for the fix!

**Comment by VesaJuvonen** [comment]
The issue still indeed exists, but should not be there within next few days.

**Comment by lahuey** [comment]
This issue should be fixed now. Please reopen the issue if you're still seeing problems

**Comment by peterremote1980** [comment]
1.5.1 still not working


	"dependencies": {
		"@microsoft/sp-core-library": "1.5.1",
		"@microsoft/sp-lodash-subset": "1.5.1",
		"@microsoft/sp-office-ui-fabric-core": "1.5.1",
		"@microsoft/sp-webpart-base": "1.5.1",
		"@types/es6-promise": "0.0.33",
		"@types/react": "15.6.6",
		"@types/react-dom": "15.5.6",
		"@types/webpack-env": "1.13.1",
		"bootstrap": "^4.1.1",
		"classnames": "^2.2.6",
		"jquery": "^3.3.1",
		"react": "15.6.2",
		"react-dom": "15.6.2"
	},
	"devDependencies": {
		"@microsoft/sp-build-web": "1.5.1",
		"@microsoft/sp-module-interfaces": "1.5.1",
		"@microsoft/sp-webpart-workbench": "1.5.1",
		"gulp": "~3.9.1",
		"@types/chai": "3.4.34",
		"@types/mocha": "2.2.38",
		"ajv": "~5.2.2"
	}
<img width="1680" alt="screen shot 2018-07-04 at 12 30 50 am" src="https://user-images.githubusercontent.com/36571333/42232718-dd5d8c4e-7f21-11e8-9b5f-48834988e1e7.png">

**Comment by cythomli** [comment]
@peterremote1980 Can you share your code?

**Comment by cythomli** [comment]
@lahuey Please reopen the issue as I still the error.

**Comment by lahuey** [comment]
@cythomli  I cannot repro this issue. Could you share your code? My email is lahuey@microsoft.com
