### ISSUE TITLE
Error in code sample Add an action button to a field (advanced)

### ISSUE THREAD

**Issue by SergePoint** [SharePoint/sp-dev-docs#2274]
In the sample code to add the email action it is missing: 
"$schema": "http://columnformatting.sharepointpnp.com/columnFormattingSchema.json",
and 
"class": "sp-field-quickAction", 
shoud be "class": "sp-field-quickActions",
If you copy the code as is in the documentation, the email icon is not shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#create-clickable-actions)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by thechriskent** [comment]
The schema has been updated and added to all samples in the documentation. Thanks for catching this!

The correct class is `sp-field-quickAction`. There is, however, an open issue (#2101) that identifies a problem with this class and displaying icons. We'll track the status of that issue over there and we'll close this one since the schema issue has been addressed. Thanks!

**Comment by Yusha813** [comment]
I'm not sure why this is marked as Closed. This is still an issue, this should be opened until the issue is resolved.

**Comment by thechriskent** [comment]
This issue was with the missing schema from the samples. This has been corrected. The other issue, is inaccurate since the correct class is `sp-field-quickAction`. However, there is another issue referenced above (#2101) that addresses the problem with this class that is preventing icons from rendering correctly. That issue will remain open until resolved.
