### ISSUE TITLE
Search limits results to 4 if I include the selectproperties query string parameter

### ISSUE THREAD

**Issue by colinrippeyfinarne** [SharePoint/sp-dev-docs#3261]
I have found a strange issue with this REST API that I can replicate on different tenants.

If I use a simple GET call such as:

https://mytentant.sharepoint.com/_api/search/query?querytext=%27conf%27&selectproperties=%27PreferredName,WorkEmail,PictureURL,WorkPhone%27&sortlist=%27LastName:ascending%27&sourceid=%27b09a7990-05ea-4af9-81ef-edfab16c4e31%27&rowlimit=500

I get back 4 results only, I should get back 6.

If I remove the selectproperties parameter I get ALL the results I expect.

To test this I created a demo tenant from the Microsoft Partner site https://demos.microsoft.com and simply searched for the text 'conf' as there are a bunch of test users that are Conf Room xxx.

I can replicate this issue on different tenants using different search terms that should return more than 4 results but each time I only get back 4 results, if I do choose to remove the selectproperties parameter I get back all the results I expect to see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b3e4019-1df2-2317-7a63-dbdfba66a3f4
* Version Independent ID: 7f409188-f8ae-94cd-d174-b0c7b5183096
* Content: [SharePoint Search REST API overview](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview)
* Content Source: [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sharepoint-search-rest-api-overview.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

**Comment by colinrippeyfinarne** [comment]
Any feeback on this?

**Comment by bcameron1231** [comment]
Hi @colinrippeyfinarne I've tried to reproduce this issue. Can you clarify, did you say all of the results get returned from the Demo tenant?

Can you provide any more information on your search environment? Using Query Rule? Use Custom Result sources?

**Comment by colinrippeyfinarne** [comment]
Hi @bcameron1231 as above I can re-create this issue on our PROD tenant.

If I can "try" to demo, the screen shot below shows me sending a query for users with the Surname Watson (that I know there are more than 4 of but the query is returning only 4):

![image](https://user-images.githubusercontent.com/37219358/52777133-0107c180-303b-11e9-8b48-f099f969b765.png)

Next, here is the exact same query but if I remove the selectproperties from the query string I get back all the results I expect:

![image](https://user-images.githubusercontent.com/37219358/52777904-c56df700-303c-11e9-8e7b-2df1cc1901e3.png)

The root of this issue is from the SharePoint Starter Kit People Directory pages. The free text search for people is only returning four results and when I am tracing the calls in fiddler I see the raw request as I've tried to explain above.

**Comment by colinrippeyfinarne** [comment]
@bcameron1231 here's another example using a simple Demo tenant I created this morning via https://demos.microsoft.com

I have the following raw url (I am searching for the letter A so expecting tons of results):

https://m365x019802.sharepoint.com/_api/search/query?querytext=%27A%27&selectproperties=%27PreferredName,WorkEmail,PictureURL,WorkPhone%27&sortlist=%27LastName:ascending%27&sourceid=%27b09a7990-05ea-4af9-81ef-edfab16c4e31%27&rowlimit=500

I see this:

![image](https://user-images.githubusercontent.com/37219358/52780464-19c7a580-3042-11e9-9943-1c2fc6521561.png)

And if I remove the selectproperties from the querystring I see this:

![image](https://user-images.githubusercontent.com/37219358/52780601-7034e400-3042-11e9-96f9-e20c86ffcade.png)

So I can recreate this, and for our site using the Starter kit it is causing an issue.

**Comment by bcameron1231** [comment]
I am at a loss... I created a new demo tenant from demos.microsoft.com this morning and I have copied your query. It returned 19 records for me...

https://m365x957771.sharepoint.com/_api/search/query?querytext=%27A%27&selectproperties=%27PreferredName,WorkEmail,PictureURL,WorkPhone%27&sortlist=%27LastName:ascending%27&sourceid=%27b09a7990-05ea-4af9-81ef-edfab16c4e31%27&rowlimit=500

![image](https://user-images.githubusercontent.com/7944457/52790674-60a6a280-3024-11e9-95e7-64131fa1322e.png)

**Comment by colinrippeyfinarne** [comment]
@bcameron1231 thanks for taking the time to check, I am at a loss too as no idea why I am seeing this either? 

Think I need to (for whatever reason) rule out the network connectivity I am going through "in case" there's some strange throttle going on (clutching at straws really).

**Comment by colinrippeyfinarne** [comment]
@bcameron1231 can you humour me for one min, in your browser session where you are seeing the 19 results, can you duplicate the tab and resubmit the query in the duplicate tab and check the results?

I am "able" to re-create the search returning all 19 results, but then if I try again in another tab it only returns 4 (tried this on chrome, firefox). If I leave both tabs open I and then after few mins I do a CTRL F5 I get back 4 in one and 19 in the other but randomly in each one, not the same tab always getting 4 and the other getting 19 (almost as if I might be hitting a different query front end each time).

I can see this behaviour this on my current client's laptop, and on my own personal laptop going out over a totally different network.

**Comment by bcameron1231** [comment]
@colinrippeyfinarne  That does it. I followed your repro steps above. It actually doesn't require a new tab. If you do Empty Cache + Hard Reload, you will get 4 returned rows, even though the query says 19 items should be returned.

@VesaJuvonen looks like this might need to be looked at more closely as a possible bug.

**Comment by colinrippeyfinarne** [comment]
@bcameron1231 thank you! At least I now know I'm not going mad lol.

**Comment by bcameron1231** [comment]
@colinrippeyfinarne Was this ever resolved in your environment?

**Comment by colinrippeyfinarne** [comment]
@bcameron1231 looks like there's been a change to the back-end and the above urls no longer work for me?

**Comment by bcameron1231** [comment]
@colinrippeyfinarne  It's likely the demo environments expired. I'm just wondering if it's been fixed on your end or if this is still an open ticket.

**Comment by colinrippeyfinarne** [comment]
@bcameron1231 no my demo tenant is still fine - I had just pasted the url into a browser window and it failed with access denied and I then "logged in properly" and tried again and I am getting the results back now. I'll need to now test if the issue is still appearing.

**Comment by colinrippeyfinarne** [comment]
@bcameron1231  looks like I'm still seeing the same issue as before, I am getting back 4 rows and (sometimes) more than 4 if I do a force refresh I get more than 4.

**Comment by bcameron1231** [comment]
@VesaJuvonen This is still an issue, and I'm actually seeing more side affects. When I query items using search (either through API, or CSWP), if I do a hard refresh, every so often the items coming back do not have a ContentType managed property with values. If I refresh a couple more times, the ContentType will populate correctly....

**Comment by mickyc1** [comment]
This is happening me on every request no matter what browser or how times I force refresh. Anyone know of any way to fix this?
