### ISSUE TITLE
Unable to add SPFx web part to classic page in RC0

### ISSUE THREAD

**Issue by zplume** [SharePoint/sp-dev-docs#343]
#### Category
- [ ] Typo
- [ ] Question
- [x] Bug
- [ ] Enhancement / Suggestion
- [ ] Additional article idea

#### Expected or Desired Behavior
SPFx web parts can be added to a classic page in RC0

#### Observed Behavior
SPFx web parts cannot be added to a classic page in RC0

#### Steps to Reproduce
- Create an SPFx web part using RC0 drop / yo generator
- Update "config\write-manifests.json" to specify a CDN path in SharePoint, e.g. "https://tenantname.sharepoint.com/sites/assets/style library/spfx"
- "gulp --ship"
- "gulp bundle --ship"
- "gulp package-solution --ship"
- Upload "sharepoint\solution\appname.sppkg" to SPO app catalog
- Upload contents of "temp\deploy" to a SPO site collection (e.g. "https://tenantname.sharepoint.com/sites/assets/style library/spfx/") 
- Install app on a test site via site contents page
- Edit the home page of the site (a wiki page)
- Open the insert web part menu
- The SPFx web part is not available to be added to the page (I also checked the insert app part menu)

Thanks

**Comment by patmill** [comment]
Is the webpart available on "modern" pages?

**Comment by zplume** [comment]
Yes the web part is available for selection on modern pages.
However I get the following error when adding the webpart to the page:
[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.HelloWorldWebPart.cde5d690-cc72-4800-a31d-e24c91fa37e5,Error: Error: Unable to load script https://tenantname.sharepoint.com/sites/Assets/SPFx/HelloWorld/hello-world.bundle Error loading https://component-id.invalid/45177f7a-648e-4c87-9c08-8386e41e2422 script resources due to: undefined. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-28.016/sp-client-base_en-us_a666e7641ac07e434cbbc25b9a2ae3f1.js:48:12396) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-28.016/sp-webpart-base_en-us_5ade5685acecf1283a7a0e6fafc6dd2c.js:47:21044) at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-28.016/sp-webpart-base_en-us_5ade5685acecf1283a7a0e6fafc6dd2c.js:47:21457) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-28.016/sp-webpart-base_en-us_5ade5685acecf1283a7a0e6fafc6dd2c.js:47:30989

I'm attempting to use SharePoint as the CDN (see URL in error above).
I notice that when I try and open the 45177f7a-648e-4c87-9c08-8386e41e2422.json file from SharePoint by clicking its name in the modern UI, I get a "File not Found" error. I can download the file successfully though, so it's definitely there.
I notice that .json is a blocked file type in SharePoint (https://support.office.com/en-us/article/Types-of-files-that-cannot-be-added-to-a-list-or-library-30be234d-e551-4c2a-8de8-f8546ffbf5b3) - does this mean it's not possible to use SharePoint as the host for SPFx web parts?

Thanks

**Comment by zplume** [comment]
I tried adding another SPFx web part to a modern page where the app is installed in the same site and the web part is configured to load from localhost (rather than from CDN).
I made sure "gulp serve" was running, but I get the following error when adding the web part to the modern page:

[SPWebPartErrorCode.ScriptLoadError]:: Unable to load web part WebPart.HelloWorld2WebPart.bac135b5-19d6-4257-9f9a-c8944ea8b2fc,Error: Error: Unable to load script https://localhost:4321/hello-world2.bundle Error loading https://component-id.invalid/d145bd52-9ec8-42d1-aac0-5751ae4b9ba1 script resources due to: undefined. CALLSTACK:: Error at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-28.016/sp-client-base_en-us_a666e7641ac07e434cbbc25b9a2ae3f1.js:48:12396) at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-28.016/sp-webpart-base_en-us_5ade5685acecf1283a7a0e6fafc6dd2c.js:47:21044) at Function.t.create (https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-28.016/sp-webpart-base_en-us_5ade5685acecf1283a7a0e6fafc6dd2c.js:47:21457) at https://spoprod-a.akamaihd.net/files/sp-client-prod_2016-11-28.016/sp-webpart-base_en-us_5ade5685acecf1283a7a0e6fafc6dd2c.js:47:30989

**Comment by zplume** [comment]
Ah, looking at your tweet it looks like RC0 isn't on the tenant yet: https://twitter.com/PatMill_MSFT/status/819613473168465925

**Comment by patmill** [comment]
We increased the rollout a bunch today, with the rest likely being upgraded early next week.

**Comment by zplume** [comment]
Ah great, I just retested:
- The web part loads successfully on a modern page
- I can't select the web part to add it to a classic (wiki) page via either insert > app part or insert > web part (it's not listed)
Both tests above were performed on the same site with the app installed via site contents.

Using SP as the CDN works, which is good news :)

Thanks

**Comment by vbartari** [comment]
For me it's not working for classic and modern pages.
Anyone have any update?
How can i see my webpart in Webpart list ..:
Please see my issue in  
https://github.com/SharePoint/sp-dev-docs/issues/353

**Comment by jaredbuttars** [comment]
I am having a similar issue with web parts on classic pages. The site is running RC0 as confirmed by the "2017" version scripts running on _layouts/15/workbench.aspx.

Using the latest RC0 bits to build the webpart, install to the store, and install to the site. The web part is not listed in the web parts list when adding a web part to the page.

Also, web parts that were previously installed and then removed are still showing in the web parts list.

**Comment by patmill** [comment]
Hi @jaredbuttars - what container are you looking for the new webparts in for your classic page scenario?

**Comment by jaredbuttars** [comment]
@patmill  I'm looking under "Custom"

**Comment by patmill** [comment]
Currently on my phone, so I'm not exactly sure what the name is. Can you check the rest of them?  Is there one called "under development"?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaredbuttars** [comment]
There is no "under development" folder.

**Comment by patmill** [comment]
Ok, super weird. My test suite was working on Friday (I have a classic page with the web part in it) but now I can't add another one. So, you aren't doing anything wrong - we are.

We will look into this tomorrow AM. In the mean time, you can test on a modern page. If you go to the site pages list view, selecting "new" then "site page" should get you a modern page.

________________________________

**Comment by jaredbuttars** [comment]
Agreed. Super weird. Even more weird, I am no longer able to create new modern pages. I tried several sites on our tenant.

**Comment by juanmlarios** [comment]
BTW I think that this is a problem with APPS being deployed through the APP Store and not through the Developer Site. Apps deployed straight into the developer site work fine in both modern and classic pages and the .webpart file is deployed to the web part gallery. The grouping that it's located in is under "Under Development". The moment you add the app to the site collection of an app deployed via the APP store, the .webpart file is not deployed and only works in Modern Pages. 

The reason some are finding the .webpart file is because it might be lingering from a previous deployment.

**Comment by patmill** [comment]
We've sorted out the issue and it should be resolved.  Can you try again and see if it is working?  The webpart should be in the "under development" section.

**Comment by zplume** [comment]
@patmill I tried redeploying the app (via the catalog)...
- make minor change to app code
- gulp bundle --ship
- gulp package-solution --ship
- delete app from site
- remove app from recycle bin
- remove app from 2nd stage recycle bin
- update app catalog with new version of package
- upload updated bundle js/json files

...and still don't see the web part as an option in classic pages > under development.

I'll try a developer site.

Thanks

**Comment by zplume** [comment]
@patmill I've tried the following:

- Create a developer site collection via https://tenantname-admin.sharepoint.com/_layouts/15/online/SiteCollections.aspx
- Create a subsite within the developer site collection ("team site" template)
- Upload the app package to the App Packages library in the developer site collection
- Navigate to the Apps in Testing library in the developer site collection
- Clicked the "new app to deploy" link
- Selected the app package that I uploaded
- Left the "Deploy app to" URL at its default value (the URL of the developer site collection)
- Clicked Deploy

This results in the error "Sorry, something went wrong. Client Side Solutions cannot be used in this location."

- I tried setting the "Deploy app to" URL to the URL of the subsite - this resulted in the same error.
- I tried setting the "Deploy app to" URL to the URL of another site collection - this resulted in the error "The install URL should reside within the Dev site collection."

Thanks

**Comment by manishgarg1** [comment]
+Graham

________________________________

**Comment by jaredbuttars** [comment]
I'm still experiencing this problem. There is no "Under Development" folder in the web part gallery and old, completely uninstalled web parts are still listed within the "Custom" folder - of course listed but not functional.

**Comment by patmill** [comment]
OK, one last time.  Apparently some tenants didn't get the fix - can you check one last time?

**Comment by jaredbuttars** [comment]
Boom! Got it! THANK YOU!

**Comment by zplume** [comment]
@patmill I can now add my web part via the "Under Development" folder on classic pages.

Thanks!

**Comment by vbartari** [comment]
updated with latest changes related to the RC0 and i'm able to see my Client webpart in all the pages classic as well as in modern.

Almost all can view this latest changes.

**Comment by manishgarg1** [comment]
Hi All, I am assuming this issue is now resolved. Please re-activate the issue if that is not the case.

**Comment by AmayKulkarni** [comment]
I AM FACING THIS ISSUE, WHILE PACKAGE IS ADDED:
Client side solutions cannot be used in this location.
