### ISSUE TITLE
Get-PnPTenantSite : System.InvalidOperationException: The type of data at position 1684 is different than the one expected.

### ISSUE THREAD

**Issue by siata13** [SharePoint/sp-dev-docs#3577]
Hi,

When try to obtain the PnPTenantSite information exception is thrown. Seems, it is related to parsing of the JSON result received from O365. I have checked the traffic with fiddler and it seems that the result coming from O365 is correct.

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

### **Steps to reproduce behavior**
Execute 'Get-PnPTenantSite' cmdlet with or without parameters.

### **Expected behavior**
Receive TenantSite / List of TenantSite objects.

### **Actual behavior**
Exception is thrown:

System.InvalidOperationException: The type of data at position 1687 is different than the one expected.
at Microsoft.SharePoint.Client.JsonReader.ReadGuid()
at Microsoft.Online.SharePoint.TenantAdministration.SiteProperties.InitOnePropertyFromJson(String peekedName, JsonReader reader)
at Microsoft.SharePoint.Client.ClientObject.FromJson(JsonReader reader)
at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
at Microsoft.SharePoint.Client.ClientRequest.d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.SharePoint.Client.ClientRequest.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.SharePoint.Client.ClientRuntimeContext.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.SharePoint.Client.ClientContext.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at Microsoft.SharePoint.Client.ClientContextExtensions.d__7.MoveNext()

**Comment by andrewconnell** [comment]
This seems related to the PnP Core PowerShell component... best to submit this question to that specific repo's issue list: https://github.com/SharePoint/PnP-Sites-Core

**Comment by siata13** [comment]
It is not related to PnP Core Powershell. Teh exception is coming from **Microsoft.SharePoint.Client.JsonReader.ReadGuid()**.

Please reopen.

**Comment by VesaJuvonen** [comment]
The issue is in the underlying CSOM APIs or specifically in the server side APIs and is being worked on. Path deployment should get on hold and canceled so we should not have new tenants experiencing this anymore. The fix is being worked on and it will be shipped server side as soon as possible, but can't provide an exact ETA at this point.  

Thanks for reporting this.

**Comment by theportalshop** [comment]
Thank you very much for addressing this.   Have a client tenant that is adversely affected by this bug.   Thanks again.

**Comment by joecmajor** [comment]
This is affecting both our Live and Production tenancy's with this issue.

**Comment by mdissel** [comment]
@VesaJuvonen any ETA / updates? We have many customers who are all having this problem when provisioning sitecollections.

**Comment by marcoschmucker** [comment]
We do have several customers, along with different DEV/ TEST and PROD tenants who are affected  when provisioning site collections.

**Comment by koskila** [comment]
Thanks for the clarification, @VesaJuvonen ! I can also confirm we have several environments being affected by this issue, so we are eagerly awaiting new updates :)

**Comment by VesaJuvonen** [comment]
Thanks, everyone for following up on this with updates. I'll try to get the latest status from owners of the issue and share it here asap.

**Comment by fredericklin** [comment]
We are being impacted as well with Azure Automation scripts that have a dependency on this functionality.

**Comment by DwayneMacisaac** [comment]
Have they considered backing out the changes on the affected Tenants, until they have a fix?

**Comment by theportalshop** [comment]
> Have they considered backing out the changes on the affected Tenants, until they have a fix?

+1 What he said.

**Comment by spkimc** [comment]
Our production and development tenants suffered this problem on March 12 - 13, but now it is no longer an issue as of March 14th.

**Comment by VesaJuvonen** [comment]
I do not have yet ETA for this, but things are actively being worked on. Thanks, everyone for the updates as they do help others to see how things are progressing cross the tenants. Transparency will reduce confusion.

**Comment by theportalshop** [comment]
> Our production and development tenants suffered this problem on March 12 - 13, but now it is no longer an issue as of March 14th.

Per what spkimc also just mentioned, my client's tenant that was experiencing the issue 12th & 13th is also no longer experiencing it today (the 14th).  Obviously no idea if that is a roll back or a fix, but its working for now so thank you very much for the support and communication.

**Comment by VesaJuvonen** [comment]
The fix is currently being rolled out worldwide, so the issue should be resolved for everyone within upcoming hours. Please do provide updates on your tenant status. If the issue still exists after a few hours, please do report that in here as well. Thanks, everyone for your activity on this.

**Comment by fredericklin** [comment]
It is working again. Thanks for the fix.

**Comment by spkimc** [comment]
Yesterday I had this error at the beginning of script when creating a site collection app catalog.  This line, $ctx.ExecuteQuery(), caused this error:
Exception calling "ExecuteQuery" with "0" argument(s): "The type of data at position 1144 is different than the one expected."  

Today, I have been successful in passing the above point in the scripts and in building a hierarchy of 6 sites but right near the end of my scripts I see it again when I am turning off minor versioning on the site pages library:  Invoke-PnPQuery : The type of data at position 1145 is different than the one expected. 

While the minor versioning is successfully turned off but this Invoke-PnPQuery is returning the above error every time.

**Comment by joecmajor** [comment]
All working again in both Production and Dev tenancy's. Many thanks for the fix and updates.

**Comment by siata13** [comment]
It is working on my tenants as well. @VesaJuvonen thank you for your help!

**Comment by tavikukko** [comment]
Get-PnPTenantSite seems to work ok now, but, you cannot create sitecollection with "publishing portal" template from admin center UI, the task never ends. To create classic teamsite, it works ok. So something to do still with activating publishing feature?

trying to create publishing portal:
![Screenshot 2019-03-15 at 10 10 11](https://user-images.githubusercontent.com/2223355/54417691-96b27180-470b-11e9-9eaa-f3e54445eca7.png)

teamsite create ok:
![Screenshot 2019-03-15 at 10 18 22](https://user-images.githubusercontent.com/2223355/54417849-f446be00-470b-11e9-9ffb-be2750fa0956.png)

**Comment by phawrylak** [comment]
@VesaJuvonen, fix doesn't seem to be rolled out to the tenant of one of our customers and it's really big problem for us, because CSOM in our app stopped working. I can send you more details about tenant, so you can verify it.

**Comment by poikjo** [comment]
I can also see issue still on my tenant.

**Comment by VesaJuvonen** [comment]
Thanks, everyone on your status updates. I'll check things internally and try to get back asap. The update is rolling out gradually, so having some tenants already working and some don't, is understandable.

**Comment by VesaJuvonen** [comment]
Quick update - Fix is still in progress to get fully rolled out, so it's understandable that some have this already fixed and it's still an issue in some tenants. The situation should be fully resolved within the next 12 hours unless there are unexpected delays.

**Comment by stvwllms** [comment]
We are not seeing the error anymore but are getting intermittent time outs on Get-PnPTenantSite, GetSPOSite...

**Comment by phawrylak** [comment]
@VesaJuvonen, unfortunately the bug is still there.

**Comment by poikjo** [comment]
My tenant is fixed.

**Comment by jimmywim** [comment]
My tenant's fixed

**Comment by swjensen** [comment]
We got the error when creating a Teams from an existing Group. The error is gone, but now we are getting this error instead:
{
  "error": {
    "code": "BadRequest",
    "message": "Entity only allows writes with a JSON Content-Type header.",
    "innerError": {
      "request-id": "0912aea8-c336-49e4-9a68-e38f0dc5577b",
      "date": "2019-03-18T11:36:35"
    }
  }
}

**Comment by DwayneMacisaac** [comment]
Still getting the error as well.  
We have had this issue for a week.  When is it going to be fixed?

**Comment by koskila** [comment]
I can confirm that this issue has been fixed on all 2 of my tenants where I saw this. While we're still experiencing issues with site provisioning, I suppose they're not connected to this particular change?

**Comment by bjdekker** [comment]
@koskila @tavikukko  we also have problems with the site provisioning of Publishing Portals, we get the same error as @tavikukko  and the site never gets created. I created a site collection without a template and tried to apply the publishing portal template after creating, but I got the following error:
![image](https://user-images.githubusercontent.com/12426259/54587123-6de9ef00-4a1f-11e9-8ec8-ac4ca8e0c80a.png)
Probably related to this:
![image](https://user-images.githubusercontent.com/12426259/54587253-d5a03a00-4a1f-11e9-9edc-209401ecce84.png)

The deployment of the fix is scheduled for 23 March, which is very late, regarding that it is impossible to create new site collections for nearly two weeks now. Can't it be deployed any sooner?

**Comment by phawrylak** [comment]
My affected tenant was finally patched.

**Comment by tavikukko** [comment]
All good here too

**Comment by VesaJuvonen** [comment]
We do understand that this was far from the optimal situation, but thanks for following up with the status updates. Based on our patch tracking, the issue should be now resolved worldwide, so closing this one. We do apologize for the inconvenience caused by this issue and are working on actions to prevent similar issues in the future.
