### ISSUE TITLE
SPFx as Teams tab - pop out tab not working

### ISSUE THREAD

**Issue by kjdahlsp** [SharePoint/sp-dev-docs#6665]
## Category

- [x] Bug

## Describe the bug

> I have an SPFx app running in Teams (TeamsTab) and SharePoint. Everything works fine except when trying "pop out tab" in Teams Desktop client, where nothing happens. I have tried updating to 1.1 and also doing an empty hello world project with the same result. 

## Steps to reproduce

> 

1. Follow https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab
2. In Teams Desktop, click pop out tab
![teams](https://user-images.githubusercontent.com/31934890/106462703-bb966600-6496-11eb-9f92-f594fa93b213.png)

## Expected behavior

> Webpart should load in a pop out window. 

## Environment details (*development & target environment*)

> 

- **Your Developer Environment**: Windows 10
- **Target Environment**: SharePoint Online
- **Framework**: Node.js 10.23.1
- **Browser(s)**: Teams Desktop Client (Microsoft Teams Version 1.3.00.34662 (64-bit)) 
- **Tooling**: SPFx v1.11.0

**Comment by raclettierer** [comment]
I have the same problem. In devtools I see a request without de tenant host -> undefined

https://**undefined**/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=....

**Comment by shajumohamed** [comment]
I have the same problem as well . The Pop out teams Teams Personal App functionality doesn't work due to this issue .

**Comment by GuillermoBas** [comment]
Same issue here. All our SPFx apps stopped showing in pop up (I'm pretty sure they were showing at some point recently in the past few months...).
We really need this core feature to be fixed to support a Team's first approach.

**Comment by jon85** [comment]
Same issue here. It was working at least a couple weeks ago, if not more recently.

**Comment by kjdahlsp** [comment]
For me, the problem was resolved in connection to https://github.com/SharePoint/sp-dev-docs/issues/6563

**Comment by GuillermoBas** [comment]
> For me, the problem was resolved in connection to #6563

Is that still working for you today? We also saw that fixed for a few months but It stopped working again recently starting in the past few weeks...

**Comment by kjdahlsp** [comment]
> > For me, the problem was resolved in connection to #6563
> 
> Is that still working for you today? We also saw that fixed for a few months but It stopped working again recently starting in the past few weeks...

Yes, at least the existing solution is still working.

**Comment by raclettierer** [comment]
@kjdahlsp   What was the solution?

**Comment by patmill** [comment]
Can you add a bit more information, like what kind of app this is?  (channel, personal, meeting, etc.)?  We have fixed some issues in the past in this area, and there is another fix currently rolling out.

**Comment by raclettierer** [comment]
In my case I have a personal app which was implemented using SPFX V 1.11.
For a few months now the pop-out shows only a blank screen

in Browser i saw a network error. I think the host will not be sumittet 

https://**undefined**/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=

**Comment by jon85** [comment]
The app we are having an issue with is standalone available from the lefthand main toolbar. I have added some info below, please let me know what else might help. Thanks!

I see the following error logged in the main teams console when i try and pop out the app or refresh the pop out:

`?agent=electron&version=21110108719:1 AuthenticationService: Authentication - {"context":"ShellService::requestMessage","subContext":"AuthElectron","message":"Received an error from IPC::{\"eventName\":\"aadGetToken\",\"error\":\"resourceRequiresConsent\",\"correlationId\":\"<removed>\"}::isOnline-true","errorCode":"RemoteOperationFailed","correlationId":"<removed>","isExpected":false}`

When I inspect the pop out, I see:

iframe id="extension-tab-frame" class="extension-tab-frame" name="extension-tab-frame" src="https://undefined/_layouts/15/TeamsLogon.aspx?SPFX=true&amp;dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=removed%26forceLocale=en-us" frameborder="0" sandbox="allow-forms allow-modals allow-popups allow-pointer-lock allow-scripts allow-same-origin allow-downloads" allow="geolocation *; microphone *; camera *; midi *; encrypted-media *;" allowfullscreen="">
    </iframe>

**Comment by shajumohamed** [comment]
> 

The issue still exists in  my solution with teams toolkit v3.1.1 .  SPFx version is 1.13.1 .  This only affects the tab with the web part . 
 
The following is the content URL for the tab  from the manifest . 

"contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=d817c1bd-e96c-44da-80cd-6f7ae91de016%26forceLocale={locale}"

I added another tab in the manifest  with a SharePoint page as the Content URL  and it is working fine . 

As a workaround can the pop out option be disabled through the manifest ?

**Comment by jon85** [comment]
@patmill anything else I can do to provide more information? 

I'm unsure how to catch the event opens the pop out, but if I check window.location.hash in  "onDOMContentLoaded" function in the iframe-container.html, I see domain is passed undefined: "#iframeurl=https%3A%2F%2Fundefined%2F_layouts%2F15%2FTeamsLogon.aspx". 

Please let me know what else I can do to help track this down. Thanks!

**Comment by patmill** [comment]
Had a whole write up with extra questions, etc. but just found the special case.  Tab apps work correctly, but personal ones don't (with the same 'undefined' URL).  Looking into it.

**Comment by jweiss-eqrx** [comment]
Yes, that's the behavior we see. Glad you were able to reproduce, thank you!

I spent a good bit of time tracing the execution of the code from the pop out event and couldn't track where the variable was getting lost. My guess/hunch is it has something to do with the fact that there is no team site for a personal app, so {teamSiteDomain} is therefore undefined.

**Comment by patmill** [comment]
It looks like a regression in how teams handles pop-outs of personal apps.  We're working with the Teams folks on getting a fix in.  I'll update here when I get a firm timeline.

**Comment by jweiss-eqrx** [comment]
excellent, thanks again!

**Comment by plodik** [comment]
Hello, any update on this feature please? It is still not working. Thanks a lot for any update.

**Comment by Tanddant** [comment]
It's working here now!

**Comment by AJIXuMuK** [comment]
@kjdahlsp @plodik @jweiss-eqrx - could you please check if it is working now for you too?

**Comment by AJIXuMuK** [comment]
@GuillermoBas - this sound not related to the pop out directly.
Could you please open a new issue?

Closing this one as the issue has been fixed.

**Comment by plodik** [comment]
> @kjdahlsp @plodik @jweiss-eqrx - could you please check if it is working now for you too?

Hello @AJIXuMuK, I can confirm it started to work immediately in my testing tenant and also in the customer's environment as well. Thanks!!!

**Comment by jweiss-eqrx** [comment]
Works! Thank you!
