### ISSUE TITLE
Gulp deploy-azure-storage uploads 0 files with SPFx 1.12

### ISSUE THREAD

**Issue by coreyroth** [SharePoint/sp-dev-docs#6847]
## Category

- [x] Bug

## Describe the bug

I have updated my projects from SPFx 1.11 to 1.12 and I noticed that no files were getting deployed to my CDN.  After investigating my pipeline logs, I saw that no files were being uploaded.   I then investigated further and I saw the same behavior.  I did a gulp clean which removed my temp/deploy folder.  Then when I run gulp bundle --ship followed by gulp deploy-azure-storage no files are uploaded because no files are present in the temp/deploy folder.

## Steps to reproduce

Therefore, I decided to start over from scratch with a new project using the [CDN Getting Started](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/deploy-web-part-to-cdn).  I created a brand new CDN following all of the instructions and I am seeing the same issue.  I've tried it with both web parts and application customizer projects.

[Repo](https://github.com/coreyroth/SPFx112DeployAzureStorage)

Here's some example output:

```
Build target: DEBUG  
[16:23:27] Using gulpfile ~/Projects/SPFx/SPFx1.12WebPart/gulpfile.js  
[16:23:27] Starting 'deploy-azure-storage'...  
[16:23:27] Starting gulp  
[16:23:27] Starting subtask 'configure-sp-build-rig'...  
[16:23:27] Finished subtask 'configure-sp-build-rig' after 3.06 ms  
[16:23:27] Starting subtask 'deploy-azure-storage'...  
[16:23:27] [deploy-azure-storage] Uploading files '**/*.*' from directory './temp/deploy/' to Azure  
[16:23:27] [deploy-azure-storage] Created container: azurehosted-webpart  
[16:23:27] [deploy-azure-storage] Uploading 0 files to Azure...  
[16:23:27] [deploy-azure-storage] Upload complete!  
[16:23:27] [deploy-azure-storage] Access your files at: https://spfxcdntest.blob.core.windows.net/azurehosted-webpart  
[16:23:27] Finished subtask 'deploy-azure-storage' after 364 ms
```

## Expected behavior

File to be created in temp/deploy, files to be uploaded to Azure storage account.

## Environment details (*development & target environment*)

- **Your Developer Environment**: Mac OS 11.2.1
- **Target Environment**:  SharePoint Online
- **Framework**: Node 12, Gulp 4
- **Browser(s)**: Edge v90
- **Tooling**: VS Code | SPFx v1.12.0

### Additional context

This worked for my project in SPFx 1.11 without issue.  I have went back and double checked and I don't think I have missed anything.  There simply aren't any files in temp/deploy, the path specified in copy-assets.json.

**Comment by coreyroth** [comment]
I did some additional testing on this today.  This really isn't an issue with the deploy-azure-storage task as it is actually an issue with gulp bundle --ship not copying the files to temp/deploy.  I tried first updating copy-assets.json to point to release/assets but it still looked in temp/deploy, but the deploy-azure-storage task still looked in temp/deploy.  I then simply ran "cp release/assets/* temp/deploy" and then ran deploy-azure-storage again and it worked as expected.  It appears the copy assets subtask of gulp bundle is not executing.

**Comment by KevinTCoughlin** [comment]
Thanks @coreyroth. I believe the problem was a hard-coded path assuming assets were still written to `temp/deploy` as you pointed out.

```ts
public async executeTask(): Promise<void> {
  if (!this.taskConfig.workingDir) {
    this.taskConfig.workingDir = this.buildConfig.distFolder;
  }
  ...
}
```

**Comment by coreyroth** [comment]
Thanks @KevinTCoughlin. Make sure there aren’t two issues. One for the hard coded path in deploy-azure-storage and one to ensure files are copied into temp/deploy (or the configured path in the JSON).

**Comment by VesaJuvonen** [comment]
This issue is intended to be part of the 1.2.1 patch release. Currently we recommend to keep on using 1.11 until further notice. We do apologize the inconvenience.

**Comment by KevinTCoughlin** [comment]
@coreyroth can you confirm this upload to Azure CDN issue is fixed in `1.12.1-rc.0` suite of packages e.g. https://www.npmjs.com/package/@microsoft/generator-sharepoint/v/1.12.1-rc.0?

Specifically:

> or the configured path in the JSON

As I think we may need to follow-up once more to patch the JSON config regression. If that is still broken, I will need more info on the solution so I can repro. Namely the JSON config customized.

**Comment by coreyroth** [comment]
Hi @KevinTCoughlin, let me give it a try.  I didn't realize rc0 was out yet.  I'm on it.

**Comment by coreyroth** [comment]
Ok.  I upgraded the generator.  Compared versions in package.json with an RC0 project and updated accordingly. Gulp clean, gulp bundle --ship.  Still nothing in temp/deploy which means zero files uploaded.  I'm using the default workingDir in deploy-azure-storage.json.

Build target: DEBUG
[15:15:11] Using gulpfile ~/Projects/spfx112rc0/gulpfile.js
[15:15:11] Starting 'deploy-azure-storage'...
[15:15:11] Starting gulp
[15:15:11] Starting subtask 'configure-sp-build-rig'...
[15:15:11] Finished subtask 'configure-sp-build-rig' after 3.37 ms
[15:15:11] Starting subtask 'deploy-azure-storage'...
[15:15:11] [deploy-azure-storage] Uploading files '**/*.*' from directory './temp/deploy/' to Azure
[15:15:11] [deploy-azure-storage] Created container: logger
[15:15:11] [deploy-azure-storage] Uploading 0 files to Azure...
[15:15:11] [deploy-azure-storage] Upload complete!
[15:15:11] [deploy-azure-storage] Access your files at: https://mycdn.blob.core.windows.net/path
[15:15:11] Finished subtask 'deploy-azure-storage' after 358 ms
[15:15:11] Finished 'deploy-azure-storage' after 364 ms
[15:15:12] ==================[ Finished ]==================
[15:15:12] Project spfx-112-rc0 version:0.0.1
[15:15:12] Build tools version:3.17.11
[15:15:12] Node version:v12.21.0
[15:15:12] Total duration:4.18 s

**Comment by lucabandMSFT** [comment]
hey @coreyroth , that could be expected as we now publish from release/assets starting from 1.12.1. Do you mind complete the process and see if gulp deploy-azure-storage still fails on you?

**Comment by coreyroth** [comment]
@lucabandMSFT ok.  I updated my workingDir to ./release/assets and ran gulp deploy-azure-storage and I can confirm that it works and the files can be retrieved from my CDN at runtime.

However, in a new project, workingDir in deploy-azure-storage.json still defaults to ./temp/deploy.  If this behavior is changing then I recommend changing the default workingDir when you scaffold a new project.  I would also include in the release notes, that users need to change this setting in existing projects in order for gulp deploy-azure-storage to work.

**Comment by KevinTCoughlin** [comment]
> However, in a new project, workingDir in deploy-azure-storage.json still defaults to ./temp/deploy

This should have been fixed to copy from `./release/assets`. I am debugging.

> change this setting in existing projects in order for gulp deploy-azure-storage to work.

Glad to hear this setting is respected to provide a workaround.

**Comment by KevinTCoughlin** [comment]
Thanks again for bringing this issue to our attention @coreyroth. `npm i -g @microsoft/generator-sharepoint@1.12.1-rc.1` contains the updated value for `workingDir` in scaffolded `deploy-azure-storage.json`. We should be able to close this issue.

**Comment by coreyroth** [comment]
@andrewconnell I would consider adding this to the release notes since anyone previously using CDN deployment will need to update deploy-azure-storage.json.

**Comment by andrewconnell** [comment]
Good suggestion... thanks for bringing the change to my attention. I've got a few other changes to docs I'm making related to 1.12.1.* and will include this in those.

**Comment by andrewconnell** [comment]
@KevinTCoughlin @lucabandMSFT 

Should this value also be updated in the **./config/copy-assets.json** file as well? I see the `deployCdnPath` for a new SPFx v1.12.1.rc.1 project still references `temp/deploy`:

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/copy-assets.schema.json",
  "deployCdnPath": "temp/deploy"
}
```

Should it now be as follows?

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/copy-assets.schema.json",
  "deployCdnPath": "releases/assets"
}
```

If not, what should it be as after running **gulp build && gulp bundle -p && gulp pacakge-soultion -p**, I only see a **./temp** folder with no **deploy** subfolder.

**Comment by coreyroth** [comment]
@andrewconnell that's what @KevinTCoughlin said was updated.  The new path that is scaffolded should be releases/assets since that's where gulp deploy-azure-storage looks now for files.  I haven't tried RC1 yet, but I'll give it a try today to validate it.

**Comment by andrewconnell** [comment]
@coreyroth I understood that change to **deploy-azure-storage.json**... I'm asking about the **copy-assets.json** file.

It appears BOTH files should point to the same path, but only the former points to the new path while the latter points to the pre-spfx-v1.12.1.rc.* path.

**Comment by coreyroth** [comment]
That's a good catch.  Since deploy-azure-storage deploys directly out of **releases/assets** is **copy-assets.json** even needed any longer?
