### ISSUE TITLE
SPFX deployed as Personal Teams Tab token error

### ISSUE THREAD

**Issue by Macro21** [SharePoint/sp-dev-docs#7499]
### Target SharePoint environment

other (enter in the "Additional environment details" area below)

### What SharePoint development model, framework, SDK or API is this about?

💥 SharePoint Framework

### Developer environment

Windows

### What browser(s) / client(s) have you tested

- [ ] 💥 Internet Explorer
- [ ] 💥 Microsoft Edge
- [X] 💥 Google Chrome
- [ ] 💥 FireFox
- [ ] 💥 Safari
- [X] mobile (iOS/iPadOS)
- [X] mobile (Android)
- [ ] not applicable
- [X] other (enter in the "Additional environment details" area below)

### Additional environment details

- Microsoft Teams Desktop
- SPFx 1.12.1
- Node.js 10.22.0

### Describe the bug / error

I have created a webpart and deployed it as an MS Teams application (personal tab). It works in Teams Web and mobile, but not in Teams Desktop. The problem is in these lines:

const prov = await this.context.aadTokenProviderFactory.getTokenProvider();
const token = await prov.getToken("https://xxxxxxx.onmicrosoft.com", false);

...and never get token or error.

In Teams Web: 
![image](https://user-images.githubusercontent.com/24574303/141515757-026f3a75-b221-4f68-bfcf-95856f85c0d3.png)

In Teams Desktop:

![image](https://user-images.githubusercontent.com/24574303/141515813-aa700a90-3b9b-4823-a0b4-bffce46341b8.png)

In SharePoint: Works.

I use an Azure Function with AAD Identity Provider:

![image](https://user-images.githubusercontent.com/24574303/141516034-9fc93a98-c65c-4c99-896d-54e1518864a5.png)

![image](https://user-images.githubusercontent.com/24574303/141516150-e3b85fc2-1327-41b9-9361-98c4ecaae38f.png)

I follow this post for Azure Function Configuration.

https://www.eliostruyf.com/securing-azure-functions-existing-azure-ad-app/

My Teams Manifest: 

{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
    "manifestVersion": "1.11",
    "packageName": "com.microsoft.teams.servicesTab",
    "id": "a97f9d9d-bcb3-4247-afa8-cfe97438e926",
    "version": "1.0.27",
    "developer": {
        "name": "Client S. Coop",
        "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
        "privacyUrl": "https://privacy.microsoft.com/en-us/privacystatement",
        "termsOfUseUrl": "https://www.microsoft.com/en-us/servicesagreement"
    },
    "name": {
        "short": "TeamsTab",
        "full": "Servicios de Client"
    },
    "description": {
        "short": "Acceso a los diferentes servicios ofrecidos por Client.",
        "full": "En esta aplicación podrás conocer y acceder a todos los servicios que dispones como parte de Client Group. Podrás filtrar por los diferentes campos por los que están etiquetados."
    },
    "icons": {
        "outline": "outline.png",
        "color": "color.png"
    },
    "accentColor": "#004578",
    "staticTabs": [
        {
            "entityId": "a97f9d9d-bcb3-4247-afa8-cfe97438e926",
            "name": "Mis documentos",
            "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=a97f9d9d-bcb3-4247-afa8-cfe97438e926%26forceLocale={locale}&inTeamsSSO=true",
            "scopes": [
                "personal"
            ]
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": [
        "*.login.microsoftonline.com",
        "*.sharepoint.com",
        "*.sharepoint-df.com",
        "spoppe-a.akamaihd.net",
        "spoprod-a.akamaihd.net",
        "resourceseng.blob.core.windows.net",
        "msft.spoppe.com"
    ],
    "webApplicationInfo": {
        "resource": "https://{teamSiteDomain}",
        "id": "00000003-0000-0ff1-ce00-000000000000"
    },
    "localizationInfo": {
        "defaultLanguageTag": "es",
        "additionalLanguages": [
            {
                "languageTag": "eu",
                "file": "eu.json"
            }
        ]
    }
}

### Steps to reproduce

1. Create one Azure Function
2. Create Azure AD App Register
2. Config authenticate for Azure Function with the Azure AD App register 
3. Try get access token in SPO
4. Deploy the webpart as Personal Tab App

**Pd: I tested in other tenant and it works in Teams Desktop and Teams Mobile.**

### Expected behavior

Get Azure Function access token in MS Teams Desktop from SPFx Webpart deployed as Teams personal tab.

**Comment by lucabandMSFT** [comment]
Hey @Macro21 , is there a reason why you had to craft the manifest manually instead of using the "sync to Teams" function in SPO app Catalog? just for testing purposes (to be sure the Teams manifest is crafted properly), could you use the "sync to Teams" function and see if that solves the issue?

**Comment by Macro21** [comment]
> Hey @Macro21 , is there a reason why you had to craft the manifest manually instead of using the "sync to Teams" function in SPO app Catalog? just for testing purposes (to be sure the Teams manifest is crafted properly), could you use the "sync to Teams" function and see if that solves the issue?

Hi! Thank you for help! I've tried it but it doesn't work.

The same code but changing the addresses works in another tenant. (With "sync to Teams" and manually)

**Comment by lucabandMSFT** [comment]
@Macro21 , thanks.
when you say "hanging the addresses", what does it mean? Also, before "syncing to Teams" in the tenant that doesn't work, did you ensure you removed the old app from the Teams App Catalog?

**Comment by Macro21** [comment]
> @Macro21 , thanks. when you say "hanging the addresses", what does it mean? Also, before "syncing to Teams" in the tenant that doesn't work, did you ensure you removed the old app from the Teams App Catalog?

Sorry for bad explication.

**In the client tenant**: 
**This works in Teams Web and Teams Mobile.**

1. Azure Function: 

![image](https://user-images.githubusercontent.com/24574303/142369713-5c58b505-20ec-4d7d-95a8-36a1d4820dc4.png)

2. AAD App:

![image](https://user-images.githubusercontent.com/24574303/142369808-9c59426e-289c-4bf2-8b27-d98be75df55d.png)

3. SPFx:

![image](https://user-images.githubusercontent.com/24574303/142369560-98dfa9dd-cd21-4532-bb97-a6bdfcb99438.png)

**In the development tenant: (My tenant):**

1. Create new Azure Function
2. Create new AAD App
3. Change the Azure Function link and resource that point to the development Azure Function and resource in the SPFx project
4. Deploy the solution in **development** app catalog, sync with Teams and all works in all devices.

**Comment by juliemturner** [comment]
I can confirm (although with a simpler test case) that the Personal App AND Teams Tab in the Teams Desktop Client is not authenticating. This is an issue that has been known for a long time. The workaround is (on the desktop client) visit a SharePoint page pinned as a Personal App (like Viva Connections Home) or a pinned SharePoint page on a tab. That page will load, get a token and then if you navigate back to the Personal App or Tab the SPFx solution it will load.

>A user [submitted this as an issue](https://github.com/pnp/spfx-reference-scenarios/issues/6) (along with other things). We have now solved all their other issues.

Personal App -> SPFx web part
![image](https://user-images.githubusercontent.com/7570936/143903915-8b99d72a-14e4-4589-875f-08c2623dedb7.png)

Teams Tab -> SPFx web part
![image](https://user-images.githubusercontent.com/7570936/143904018-57edf43f-be7f-444d-8f12-c76fa1cdd8c6.png)

**Comment by lucabandMSFT** [comment]
hey @juliemturner , I want to be sure I understand the scenario you are describing here as this should no longer be the case considering all the recent updates we introduced in this code path:

- create a Teams personal app using SPFx (supportedhost == "TeamsPersonalApp")
- code attempts to call a 3rd party API using AADHTTPClient class
- once done, the solution is deployed in the SPO App Catalog and the manifest is generated in Teams using "Sync to Teams" option
- you install the app in Teams.

at that point it will work in Teams web but not in Teams Desktop.. is that correct?

thanks

**Comment by juliemturner** [comment]
Not exactly no. You can see the source code (plus pre-built sppkg file) for the entire solution here: https://github.com/pnp/spfx-reference-scenarios/tree/main/samples/ace-teams-covid/covid-spfx/teams

 ✔ create a Teams personal app using SPFx (supportedhost == "TeamsPersonalApp")
 ❌ code attempts to call SharePoint and Graph endpoints, not custom secured endpoint with AADHTTPClient 
 ❌ the solution is deployed into the SPO App Catalog but this is a custom manifest because it has custom icons, but is deployed using Sync to Teams -- which succeeds
 ✔ app is install in Teams

And then yes, at that point it will work immediately with Teams web but not in Desktop *UNLESS* you visit a SharePoint page which then authenticates you and everything starts working.

The user I mentioned was making a custom manifest, not sync to teams because they wanted to change the site collection that the app shows up in, so they followed this guidance: https://github.com/pnp/spfx-reference-scenarios/tree/main/samples/ace-teams-covid#custom-manifest

**Comment by lucabandMSFT** [comment]
so.. that seems to fail by design? :-)

by looking at the manifest you provided in the link above I see you are missing this key part:


without it, we revert back to the old "you need to be auth. in SPO in order to continue" path. By simply adding the text above in the Teams manifest should fix the issue by using the new auth code path.

"webApplicationInfo": {
"resource": "https://{teamSiteDomain}",
"id": "00000003-0000-0ff1-ce00-000000000000"
}

Can you please try?

**Comment by juliemturner** [comment]
Those additional values in the manifest don't appear to make any difference.

 - I updated the version of the teams manifest so that I could validate the new manifest was published in the Teams admin center.
 - Forcefully shut down and logged out of the Teams Desktop client to verify there was no caching issues.

Still the same problem.

**Comment by lucabandMSFT** [comment]
did you remove the app from Teams and add it back? sorry.. I'm asking this because I know that Teams is pretty ... "opinionated" :-) on the way it handles manifest caching. I would:

- remove the old manifest from the Teams app catalog
- that will remove the app from everywhere
- add the new manifest
- add the app back as personal app

and then see if that works

**Comment by juliemturner** [comment]
Well cool, that seems to have fixed it.

That said [this documentation needs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions) to be updated to indicate that you need that value for non AADHTTPClient solutions as that is really not clear as [this documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo) gives the impression that it's only for your custom secured endpoints although now that you give me the values for it I can totally see why it would be needed.

**Comment by juliemturner** [comment]
I wonder if @Macro21 is suffering from a problem with their ability to auth with that endpoint because it's using a separate AAD App Reg.. i.e. you can only put 1 in your teams manifest and if he has a custom secured application that uses a different app registration maybe that's why SSO in the client desktop isn't working....

**Comment by lucabandMSFT** [comment]
Thanks @juliemturner : I've committed a change for this [doc](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/deployment-spfx-teams-solutions) that specifies the need of that entry in the manifest to have auth working on Teams rich clients. Changes will go live as soon as my change gets approved.

@Macro21, are you able to make the same changes that helped Julie's scenario?

**Comment by Macro21** [comment]
Hi! 
First, thanks for help.

Steps I followed this morning:

1. To avoid errors, I created another project that I deployed using "Sync to teams" like @lucabandMSFT recommends. 
2. The new app works on web and mobile. (**Remember that in my development environment the same solution works in all scenarios.**)
3. To solve the problem in desktop Teams I have tried @juliemturner solution (_The workaround is (on the desktop client) visit a SharePoint page pinned as a Personal App (like Viva Connections Home) or a pinned SharePoint page on a tab. That page will load, get a token and then if you navigate back to the Personal App or Tab the SPFx solution it will load._):
     
![image](https://user-images.githubusercontent.com/24574303/144018709-b3934503-baf6-44b7-9ca8-0284e2696d29.png)
![image](https://user-images.githubusercontent.com/24574303/144018819-37cc4037-67d1-42a8-acf3-6973a9e881d3.png)
![image](https://user-images.githubusercontent.com/24574303/144019398-5c8d0276-c0b0-416d-875d-3fb1bcaf381f.png)
![image](https://user-images.githubusercontent.com/24574303/144019426-9f583b2d-363a-4b6d-af33-a2fc82433d2c.png)
![image](https://user-images.githubusercontent.com/24574303/144019567-bef2a2b3-e298-4bee-9658-e57cc9e72b3c.png)

Am I doing something wrong, @juliemturner ?

This is the new project deployed as personal app and teams tab:

![image](https://user-images.githubusercontent.com/24574303/144020286-021b1269-05e5-4352-8602-864217ddeea2.png)
![image](https://user-images.githubusercontent.com/24574303/144020593-8bd7e0df-9765-40ea-8ac6-076dccade22f.png)

And the code: 

![image](https://user-images.githubusercontent.com/24574303/144020700-8c5d2fe9-3935-45fe-8992-2cdbec663753.png)

**Comment by Macro21** [comment]
> @Macro21 -- I can try and shed some light but I probably do not have all the answers. This section:
> 
> ```json
> "webApplicationInfo": {
>    "resource": "https://{teamSiteDomain}",
>    "id": "00000003-0000-0ff1-ce00-000000000000"
> }
> ```
> 
> says that the resource needs to have access to the AAD app registration with an id of `00000003-0000-0ff1-ce00-000000000000`. Given what I know of how the tokens work in SPFx and if you look in AAD in your tenant, not in the App Registrations section (where your app for your Azure Function is likely registered) but in the Enterprise applications section you will find that id registered to an app called `Office 365 SharePoint Online`. ![image](https://user-images.githubusercontent.com/7570936/144080241-83ff242e-e470-4e77-8c59-df0d80cad386.png)
> 
> Per my previous comments I did not know for SSO to work in the Teams Desktop client that webApplicationInfo would need a reference to that app registration because the documentation implication as I mentioned to @lucabandMSFT implied it was only used to do SSO when using the AADHTTPClient in SPFx which my solution is not... this is why, when I added that to my manifest my solution started to work, because it had a pointer to where it needs to go to get a SSO token. What I think you would need to do to get the AADHTTPClient to work is to modify the id, not with the value of the Office 365 SharePoint Online enterprise app registration id, but with the app registration that was created for your Azure Function. HOWEVER, what I was saying to @lucabandMSFT above is that that section of the Teams manifest only allows for one entry, it's not an array. So, I think if you do change it and it works you will not be able to access the Microsoft Graph or SharePoint endpoints through the SPFx HTTPClients (SPHTTPClient or GraphHTTPClient). And further, if your solution does access those it may still not work and you wouldn't really know it because you'd be changing one security token error for another... @lucabandMSFT would have to confirm, or you could test it. If that's not a need of your application, then I would say that might be the fix for you.

Yes, I understand that the GUID refers to an enterprise application in the AAD and that it gives you access to the Graph API and SPO resources.

Before opening this thread I already tried adding the GUID of the application I have registered myself in the AAD, but it didn't work. 

At the moment in my solution I don't need Graph or SPO calls, but my own application can grant those permissions for Graph or SPO if needed, right?

In any case, it doesn't matter, because setting another GUID has no effect.

The real question is: Why in my development tenant it works and in the client one it doesn't?

Thank you very much for your help. :)

**Comment by juliemturner** [comment]
Yes, you are probably entirely correct about being able to grant access to the SP and Graph resources within your own app registration, I hadn't thought of that.

Re that you had already tried that, my apologies, although I read the thread I originally missed where you shared that information. So effectively in your development tenant using the Enterprise App registration Id in the Teams Manifest allows you to access even the Azure Function, that's interesting. I would have thought to make that work you would have had to have granted that enterprise app access to your Azure Function (similar to your scenario of adding SP and Graph resources to your registration). Regardless at this point your question is beyond my abilities to provide insight, hopefully on of the Microsoft people can think of something else.

**Comment by lucabandMSFT** [comment]
So.. it's not magic :): what we are doing here is basically implemented the same SSO flow that Teams had for rich client as described [here](https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso).

When SPFx detects that it is running on Teams rich clients, we use that flow to get a token for SPFx application principal and then we exchange that to every token that was approved for SPFx components (via the API access page in SPO tenant admin).

Because we use SPO as a "broker" to access other resources, SPO is the only one that needs to be registered inside Teams manifest.

@Macro21 : when you say: 
"To avoid errors, I created another project that I deployed using "Sync to teams" like @lucabandMSFT recommends.
The new app works on web and mobile. (Remember that in my development environment the same solution works in all scenarios.)"
does it mean that it solves the problem?

Would be possible for us to take a look at the environment where the problem occurs and collect logs?

**Comment by juliemturner** [comment]
So, to clarify @lucabandMSFT you're saying that you only need to add the id of the Office 365 SharePoint Online app registration and that any other app registration you have for AADHTTPClient will get the token it needs.  That is helpful to have shared, I hope you added that point to the documentation.

**Comment by lucabandMSFT** [comment]
yes @juliemturner , that is correct (and we are talking about the flow from the Teams rich clients here.. web is a different story).

and Yes: I added that to the documentation: waiting for that to be approved then it will go live

**Comment by Macro21** [comment]
> 

@lucabandMSFT _"does it mean that it solves the problem?"_ : 

In my development environment it has always worked.
In fact, in the development environment I use two tenants and it is a much more complicated scenario and it still works:

![image](https://user-images.githubusercontent.com/24574303/144202128-218f1579-74eb-4242-88cc-664ac244666f.png)

In the client tenant (just one tenant):

![image](https://user-images.githubusercontent.com/24574303/144202202-c5862758-2e06-40aa-9989-8556700c80ba.png)

As a workaround what I have done is to redirect to an SPO page within the code when detecting that we are in Teams Desktop. 
At the moment this works because we don't have more client requirements:

![image](https://user-images.githubusercontent.com/24574303/144202854-2f2fe968-16b8-4594-946e-5bb4a8a73c59.png)

@lucabandMSFT _"Would be possible for us to take a look at the environment where the problem occurs and collect logs?"_ : 
Sorry, it is not possible because it is the customer's production environment. 

In any case, the alternative solution mentioned above works (Cause is not a Teams enviroment, is a SPO page without Teams context).
If in the future they need this to work, the customer should open a ticket to support and try to solve the problem that way.

Thank you very much for your help @lucabandMSFT and @juliemturner

**Comment by patmill** [comment]
Thanks @Macro21 .  We'll close this for now, but we have made a note of the scenarios, and are working on the improved docs.
